### ISSUE TITLE
Componente de Status

### ISSUE THREAD

**Issue by GustavoZeglan** [GustavoZeglan/chimp-tamagochi#4]
### Implemente um componente de status.

O componente deve conter as seguintes props: 

- title: string
- image: string
- value: number

O design tem que ser similar a este: 
![Group 25](https://github.com/user-attachments/assets/f461582e-61d6-4e07-89cf-9cc5fd5ed686)

Use o seguinte BackgroundImage: 
![GUI 4](https://github.com/user-attachments/assets/662a5a0a-0422-49f5-87ca-a0d8898113bd)

**Comment by vinic1u** [comment]
Tarefa feita e enviada na Branch "4-componente-de-status"
